### PR TITLE
Translate to spanish

### PR DESCRIPTION
**Pull request by wfpaisa**

### CODE REVIEW

**Comment by wfpaisa** [comment]
> [CLA assistant check](https://cla-assistant.io/RocketChat/Rocket.Chat.Livechat?pullRequest=413)
> All committers have signed the CLA.

Done!

**Comment by renatobecker** [comment]
@wfpaisa can you, please, fix the conflicts here?

**Comment by wfpaisa** [comment]
Ok, fix it

**Comment by wfpaisa** [comment]
@renatobecker could you approval please :smile:

**Pull request merged**
