### PR TITLE
[IMPROVE] Allow to hide "chat button", "minimize chat" button and "expand chat" button

### LINKED ISSUE #541: Allow to hide "chat button", "minimize chat" button and "expand chat" button
I have an application which fully controls the livechat via https://docs.rocket.chat/api/livechat-api .
By default, the application hides the widget:
```
this.hideWidget();
```
Then, when the user asks for the livechat, the application calls:
```
this.showWidget();
this.maximizeWidget();
```

I want to remove "chat button", "minimize chat" button and "expand chat" buttons:
Screenshot from 2020-12-26 19-35-45
Screenshot from 2020-12-26 19-37-58

Could these options be added to `theme` apis?

### PR DESCRIPTION
**Pull request by reda-alaoui**
Fixes #541

### CODE REVIEW

**Comment by xkungfu** [comment]
hi,I modyfied the files according this improvement.
but the button still show on page bottom.
how can I enable hide the button?

**Comment by reda-alaoui** [comment]
Hi,

You must call setTheme widget function like this:
```javascript
RocketChat(function(){
  this.setTheme({
    hideChatButton: true,
    hideMinimizeChatButton: true,
    hideExpandChatButton: true
  });
});
```

**Comment by xkungfu** [comment]
> Hi,
> 
> You must call `setTheme` widget function like this:
> 
> ```js
> RocketChat(function(){
>   this.setTheme({
>     hideChatButton: true,
>     hideMinimizeChatButton: true,
>     hideExpandChatButton: true
>   });
> });
> ```

thank you very much!

**Comment by xkungfu** [comment]
> Hi,
> 
> You must call `setTheme` widget function like this:
> 
> ```js
> RocketChat(function(){
>   this.setTheme({
>     hideChatButton: true,
>     hideMinimizeChatButton: true,
>     hideExpandChatButton: true
>   });
> });
> ```

I have troubled about how to use.

where can I add  this code? Rocket.chat server or livechat client?
which file can I add?

I thought it is simple at first. but after lots of tests, after I added the codes everywhere, but no one worked,
and I didn't find one example in project files.
now I have to ask how to use this codes?

excuse me.thanks again.

**Comment by reda-alaoui** [comment]
Everything is explained at https://docs.rocket.chat/api/livechat-api

**Comment by xkungfu** [comment]
> Everything is explained at https://docs.rocket.chat/api/livechat-api

I have found this page before, but didn't know how to use.
and finally I found that the code running outside livechat and must in production package. and this is my question.
now I build a production package, and add the code to "index.html".
thank you very much!

**Comment by renatobecker** [comment]
> Fixes #541

Can you, please, fix the conflicts? 

Thanks.

**Comment by reda-alaoui** [comment]
Yes, on it

**Comment by reda-alaoui** [comment]
Conflicts fixed :)

**Comment by renatobecker** [comment]
> Conflicts fixed :)

I have a question:
Why did you implement `hideChatButton` as a prop if we already have proper methods to hide/show the widget button?
https://docs.rocket.chat/api/livechat-api#change-widget-visibility

**Comment by reda-alaoui** [comment]
> Why did you implement hideChatButton as a prop if we already have proper methods to hide/show the widget button?

I considered it was part of the theme section. Also, I don't think a dynamic toggle makes sense here.

**Comment by backspace420** [comment]
I tried it also but the button doesn't hide. I need to hide the button when the chat is maximized.

**Comment by tiagoevanp** [comment]
Hey @reda-alaoui thanks for your contribution, but we already have proper methods to hide/show the widget button. I don't think is really necessary to introduce a similar behavior on theme section of Livechat settings. To emulate this behavior, you can call the method on onload event from your page where is embed Livechat.

**Pull request closed without merging**
