### PR TITLE
[NEW] adding support for RichMessages 

### PR DESCRIPTION
**Pull request by murtaza98**
The main goal is to add support for RichMessages in Livechat.

Demo for the results so far
image

Tasks:-
- [x] Create a new RichMessageGroup Component
- [x] Link RichMessageGroup with rest of the components
- [ ] Add onClick Listeners to RichMessage Buttons
- [ ] Link RichMessageGroup component with LiveChat API

### CODE REVIEW

**Comment by renatobecker** [comment]
Hi @murtaza98 I'm really glad to know that you're willing to work on `Rich Messages` stuff.
The fact is we already have a prototype for  the `Rich Messages` design, as you can see below:

Screen Shot 2020-05-09 at 11 23 11
Screen Shot 2020-05-09 at 11 22 59
Screen Shot 2020-05-09 at 11 22 53
Screen Shot 2020-05-09 at 11 22 47

So, to be able to accept this implementation we'll need to follow the design system created for this feature.
I can share it with you if you're interested to implement the `Rich Messages` components according to the the design system expected.

**Comment by murtaza98** [comment]
Hey, @renatobecker Thanks for the feedback.
Yes, it would be helpful, if u share the expected design system. I will try to implement it :)

**Comment by murtaza98** [comment]
Also a quick question, 
I found [this](https://github.com/WideChat/Rocket.Chat.Android/wiki/Phase-1--Rich-Messaging-Acceptance-Test) article ... it's of RocketChat's Android app.

It says that the rich messages content, which we receive from RC server, it will be a part of **attachments** -> **actions** property of message object, something like this
```
message Object
{
  "alias": "Gruggy",
  "roomId": "Xnb2kLD2Pnhdwe3RH",
  "text": "Sample message",
  "attachments": [
    {
      "actions": [
        {
          "type": "button",
          "text": "Rich Message Option 1",
          "url": "http://www.kayak.com",
          "is_webview": false
        }
        {
          "type": "button",
          "text": "Rich Message Option 2",
          "url": "http://www.kayak.com",
          "is_webview": false
        }
      ]
    }
  ]
}
```

So is that correct?

**Comment by ggazzo** [comment]
check ui-kit on rocket.chat

**Pull request closed without merging**
