### PR TITLE
[IMPROVE] Allow to programmatically send a message

### PR DESCRIPTION
**Pull request by reda-alaoui**
This PR allows the CRM application to programmatically send a message on the helped user behalf.

### CODE REVIEW

**Comment by rafaelblink** [comment]
Hi @reda-alaoui, could you improve the PR description?

**Comment by reda-alaoui** [comment]
Hi @rafaelblink , I just did.

**Comment by dlecan** [comment]
Very useful!
Is it possible to merge it?

**Comment by reda-alaoui** [comment]
At the time this PR was created, when an end user opened a livechat, nothing was happening on the agent side. The end user had to send a message to catch the attention of an agent.
This PR awas created for this use case.

**Comment by cauefcr** [comment]
Dear reda-alaoui, we thank you for your efforts in trying to improve rocket.chat, and take time to evaluate every PR, but this functionality would not be a good fit to the product, as it is akin to man-in-the-middle attack on the user, impersonating him, and could be used maliciously, therefore we will not be merging the code at this time. Thank you again for your contribution :)

**Pull request closed without merging**
