### PR TITLE
[IMPROVE] Allow more email domains on Livechat registration

### PR DESCRIPTION
**Pull request by Deepak-learner**
#561 [FIX] Email-validation
Done email validation in offline registration form .
Screenshot 2021-03-16 at 2 19 41 PM
'send' button is activated for correct email address .

### CODE REVIEW

**Comment by Deepak-learner** [comment]
@rafaelblink please review .

**Comment by Deepak-learner** [comment]
@rafaelblink @murtaza98 please review.

**Comment by murtaza98** [comment]
@Deepak-learner I don't think an email is now considered valid if it doesn't have a TLD.

You can also also check this on any online validation website. I used this eg: :point_down: 

image

**Comment by Deepak-learner** [comment]
In rocket chat web app , it's accepting "test@test" email address and saving the details in contact list .
Screenshot 2021-03-18 at 2 31 02 PM
Also in this link : https://en.wikipedia.org/wiki/Email_address#Examples , check 'Valid email addresses' section  , its mention 
"admin@mailserver1" is valid email address . 
@murtaza98 , @rafaelblink can you please confirm once , particular this email address format is valid or not  as it is  also use in rocket chat web desktop app as shown in above image.

**Comment by cauefcr** [comment]
Hey people, this PR and its discussion got me in the middle of a RFC rabbit hole, and from what i can tell, [here](https://datatracker.ietf.org/doc/html/rfc2822#section-3.4.1) is the first grammar definition of an e-mail address, as addr-spec, but a few following RFCs made changes to it, like [here](https://datatracker.ietf.org/doc/html/rfc5322#section-3.4.1), allowing changes in implementation, to guarantee it's working on the specific app's context. Internationalization is another concern, as I've found no regex capable of dealing with all internationalization problems. According to [this](https://www.regular-expressions.info/email.html) website is not even possible to trust the standard regex given by IETF [here](https://tools.ietf.org/id/draft-seantek-mail-regexen-03.html#rfc.section.5). As the official recommended regex engine won't even work in Javascript, the best suggestion I have for now is the regex below, found [here](https://emailregex.com/), and that's not even talking about security implications of over-matching or frustration from users in under-matching.
```regex
/^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/
```
I don't believe there is a right answer here, what do you all think?

**Comment by KevLehman** [comment]
Well, we should use the one provided by IETF (as its "standard"). Anyways, we should be consistent 🤔 so let's give this a closer look

**Comment by cauefcr** [comment]
Hey, after raising the issue of regex e-mail validation with our team the great @KevLehman made changes on the main product, which i have copied over to this repo, on PR https://github.com/RocketChat/Rocket.Chat.Livechat/pull/693, thank you for reporting the problem!

**Comment by bastelix** [comment]
image

I get this every try .. cannot disable email and no email will accepted. Very buggy.

**Comment by bubble0h7** [comment]
> I get this every try .. cannot disable email and no email will accepted. Very buggy.

@bastelix I managed to fix this issue by setting the "Email Address to Send Offline Messages" field in the `Omnichannel > Livechat Appearance > Omnichannel offline` settings. Not the most helpful error message though.

**Pull request closed without merging**
